const sb=window.supabase.createClient(window.PRAKSH_SUPABASE_URL,window.PRAKSH_SUPABASE_KEY);let allCustomers=[];let busy=false;
async function guard(){const {data}=await sb.auth.getSession();if(!data.session){location.replace('owner-login.html');return false}const {data:r,error}=await sb.rpc('is_owner');if(error||r!==true){await sb.auth.signOut();location.replace('owner-login.html');return false}return true}
async function loadOwner(){if(busy)return;if(!(await guard()))return;busy=true;$('refresh').disabled=true;try{const {data,error}=await sb.rpc('owner_dashboard');if(error)throw error;if(!data?.ok)throw Error(data?.error||'Unable to load dashboard.');$('customers').textContent=data.stats.customers;$('pendingBillsCount').textContent=data.stats.pendingBills;$('issued').textContent=data.stats.issued;$('ownerRedeemed').textContent=data.stats.redeemed;renderPending(data.pending||[]);allCustomers=data.customers||[];renderCustomers()}catch(x){showMsg($('ownerMsg'),x.message,true)}finally{busy=false;$('refresh').disabled=false}}
function renderPending(rows){$('pending').innerHTML=rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.bill)}</td><td>${money(x.amount)}</td><td>${esc(x.date)}</td><td><button type="button" data-action="view" data-path="${esc(x.photo_path||'')}" ${x.photo_path?'':'disabled'}>View</button></td><td class="actions"><button type="button" data-action="approve" data-id="${esc(x.id)}">Approve</button><button type="button" class="danger" data-action="reject" data-id="${esc(x.id)}">Reject</button></td></tr>`).join('')||'<tr><td colspan="7">No pending bills.</td></tr>'}
async function viewBill(path){if(!path)return;const {data,error}=await sb.storage.from('bill-photos').createSignedUrl(path,300);if(error)return showMsg($('ownerMsg'),error.message,true);window.open(data.signedUrl,'_blank','noopener,noreferrer')}
function renderCustomers(){const q=($('search').value||'').trim().toLowerCase();$('customersTable').innerHTML=allCustomers.filter(x=>(x.name+' '+x.phone).toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.bills)}</td><td>${esc(x.earned)}</td><td>${esc(x.redeemed)}</td><td>${esc(x.available)}</td></tr>`).join('')||'<tr><td colspan="6">No customers found.</td></tr>'}
async function approveBill(id){if(!confirm('Approve this bill and issue points?'))return;try{const {data,error}=await sb.rpc('approve_bill',{p_bill_id:id});if(error)throw error;if(!data?.ok)throw Error(data.error);showMsg($('ownerMsg'),'Bill approved.');await loadOwner()}catch(x){showMsg($('ownerMsg'),x.message,true)}}
async function rejectBill(id){const reason=prompt('Reason for rejection:','Bill could not be verified');if(reason===null)return;try{const {data,error}=await sb.rpc('reject_bill',{p_bill_id:id,p_reason:reason});if(error)throw error;if(!data?.ok)throw Error(data.error);showMsg($('ownerMsg'),'Bill rejected.');await loadOwner()}catch(x){showMsg($('ownerMsg'),x.message,true)}}
$('pending').addEventListener('click',e=>{const button=e.target.closest('button[data-action]');if(!button)return;const action=button.dataset.action;if(action==='view')viewBill(button.dataset.path);if(action==='approve')approveBill(button.dataset.id);if(action==='reject')rejectBill(button.dataset.id)});
$('refresh').addEventListener('click',loadOwner);$('search').addEventListener('input',renderCustomers);$('logout').addEventListener('click',async()=>{await sb.auth.signOut();location.replace('owner-login.html')});$('theme').addEventListener('click',toggleTheme);loadOwner();
